"""empty message

Revision ID: 2a513f9c2625
Revises: 9e2cfebb7d7a
Create Date: 2020-09-22 12:41:36.352314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a513f9c2625'
down_revision = '9e2cfebb7d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
